# Site settings
title: Linea
email: your-email@domain.com
description: > 
  My journey stars the sea.       
baseurl: "" 
url: "http://lllinea.github.io"
github_username:  LLLinea

# Build settings
markdown: smackdown
