# Site settings
title: Yasyi
email: your-email@domain.com
description: > 
  Old people often say that love is companionship     
baseurl: "" 
url: "http://yasyi.io"
github_username:  LLLinea

# Build settings
markdown: kramdown
