# Site settings
title: sssSSSay
email: your-email@domain.com
description: > 
  请在根目录下_config.yml中修改简介
baseurl: "" 
url: "http://sssSSSay.github.io"
github_username:  sssSSSay

# Build settings
markdown: kramdown
