# Site settings
title: sssSSSay
email: your-email@domain.com
description: > 
  In me the tiger sniffs the rose.
baseurl: "" 
url: "http://sssSSSay.github.io"
github_username:  sssSSSay

# Build settings
markdown: kramdown
