# Site settings
title: yasyi
email: your-email@domain.com
description: > 
  Old people often say that love is companionship     
baseurl: "" 
url: "http://LLLiena.github.io"
github_username:  LLLinea

# Build settings
markdown: kramdown
