# Site settings
title: 顾然.
email: your-email@domain.com
description: > 
  自己满身灰暗还想着给别人一些光亮.
baseurl: "" 
url: "http://LLLinea.github.io"
github_username:  LLLinea

# Build settings
markdown: kramdown
